
CREATE DATABASE PETHAPPY
GO
USE PETHAPPY
GO
--CREAR TABLA CLIENTE--
CREATE TABLE CLIENTE
(
   IDCLI INT IDENTITY(1,1),
   NOMCLI VARCHAR(60),
   APECLI VARCHAR(80),
   DNICLI CHAR(8),
   CELCLI CHAR(9),
   EMACLI VARCHAR(40),
   DIRCLI VARCHAR(80),
   ESTCLI CHAR(1) DEFAULT 'A' --AGREGAR POR DEFAULT A(ACTIVO)
   CONSTRAINT IDCLI_PK PRIMARY KEY(IDCLI)
)
GO


--CREAR TABLA VENDEDOR--
CREATE TABLE VENDEDOR
(
   IDVEN INT IDENTITY(1,1),
   NOMVEN VARCHAR(60),
   APEVEN VARCHAR(80),
   DNIVEN CHAR(8),
   CELVEN CHAR(9),
   EMAVEN VARCHAR(40),
   DIRVEN VARCHAR(80),
   TIPVEN CHAR(1) DEFAULT 'A'--AGREGA POR DEFAULT EL ESTADO A(ACTIVO)
   CONSTRAINT IDVEN_PK PRIMARY KEY(IDVEN)
)
GO

GO
--CREAR TABLA PRODUCTO--
CREATE TABLE PRODUCTO
(
   CODPRO CHAR(4),
   NOMPRO VARCHAR(60),
   DESPRO VARCHAR(80),
   FECPRO DATETIME DEFAULT GETDATE(),
   MARPRO VARCHAR(50)
   CONSTRAINT CODPRO_PK PRIMARY KEY(CODPRO)
)
GO

--CREAR TABLA VENTA--
CREATE TABLE VENTA
(
   CODPRO CHAR(4),
   IDCLI INT,
   FECPRO DATETIME DEFAULT GETDATE(),
   CONSTRAINT CODPRO_PK PRIMARY KEY(CODPRO)
)
GO

--CREAR TABLA VENTADETALLE--
CREATE TABLE VENTADETALLE
(
    CODPRO CHAR(49),
	NOMPRO VARCHAR(50),
	PRECPRO DECIMAL,
	TIPPRO CHAR(1)

   
   CONSTRAINT _PK PRIMARY KEY()
)
GO

--REALCION DE TABLAS
ALTER TABLE REGISTRO
    ADD CONSTRAINT PARTICIPANTE_REGISTRO
	FOREIGN KEY (IDPAR)
	REFERENCES PARTICIPANTE (IDPAR)








UPDATE CLIENTE
    SET NOMCLI = 'Alexander'
    WHERE CODCLI = 'C001'
GO
Eliminar registros de tabla CLIENTE

DELETE FROM CLIENTE
    WHERE CODCLI = 'C002'
GO